// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmmzjhxbqiagzbwjkyqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbXpqaHhicWlhZ3pid2preXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzA4MzYsImV4cCI6MjA3MzQwNjgzNn0.iqtKYlGHsmvR1-m2WJTVRTGNagBnrKNHPeVdyLUM2SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});